/* This file was generated by a script using the amg_base_prec_type.F90 file as a basis. */
#ifndef AMG_CONST_H_
#define AMG_CONST_H_
#ifdef __cplusplus
extern "C" { 
#endif
#define AMG_VERSION_STRING_ ( "1.0.0" )
#define AMG_VERSION_MAJOR_ ( 1 )
#define AMG_VERSION_MINOR_ ( 0 )
#define AMG_PATCHLEVEL_ ( 0 )
#ifdef __cplusplus
}
#endif
#endif
